- .neutrinorc.js
**Closes Issue:** #8 
only show components that have a README in the styleguide and avoid rendering the others
- added `skipComponentsWithoutExample: true` to styleguide configuration
- styleguide skips components without examples (no README files)
> Only show SchemaTable in the styleguide

- .neutrinorc.js
- package.json
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
- yarn.lock
**Closes Issue:** #10 
set linting rule to use React.Fragment over shorthand syntax
- override @airbnb lint config's `react/jsx-fragments` to use React.Fragment instead
- error message prints when using `<>` syntax
> Fix eslint config to use React.Fragment over shorthand

- .neutrinorc.js
- src/components/SchemaTable/index.jsx
**Closes Issue** #18 
- linting should enable `no-use-before-define` rule for functions
- rules for variables, classes, etc. should remain the same and print error in cases of usage before definition
- added `no-use-before-define` rule
- `functions` are ignored even if referenced/used before declaration
```js
// correct use
f();
function f() {}
```
- methods within `SchemaTable` component now use the `function` syntax rather than arrow-function syntax
> Fix Eslint to allow function use before definition

- src/components/SchemaTable/index.jsx
- src/index.jsx
- src/theme.js
**Closes Issue** #12 
configure SchemaTable component's styling based on `material-ui` default theme
> Add material-ui default theme

- src/components/NormalLeftRow/index.jsx
- src/components/SchemaTable/index.jsx
**Closes Issue** #20 
find a more consistent way of conveying types between default types and array, object types while also replacing the use of `"..."`
- types are now explicitly declared in the left panel
- `"..."` usage is replaced by a highlighted text
- ex. `string`
> Find more consistent way to display types

- package.json
- schemas/basicDataTypes/array/additionalItems.json
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/README.md
- src/components/SchemaTable/index.jsx
- yarn.lock
**Closes Issue** #13 
create a method to render array type schemas
- encapsulated between `[` and `]`
- each of the array items should call on renderSchema
> Create renderArray() method

- package.json
- schemas/basicDataTypes/array/additionalItems.json
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/README.md
- src/components/SchemaTable/index.jsx
- yarn.lock
Reverts taskcluster/material-ui-json-schema-viewer#27 (Revert "Create renderArray() method" merge)
**Result**
reverts back to status where #17 is merged into `master` branch (and also which is where some changes made in #25 are mistakenly overridden)
**Reasoning**
Initially, #27 was created to revert the merge of #17 (since #17 overrode some changes created in #25 and thus, changes of #25 were not applied to the master branch).
But since the changes in #25 are relatively small (just a few lines of code), it seems more efficient to revert back to the original state (where changes were overridden) and just simply apply the few lines of code instead. This helps to avoid over-complicating the commit history while still maintaining the overall changes made from #17 and #25.
> Revert "Revert "Create renderArray() method" merge"

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
**Closes Issue** #22 
fix right panel's display of keywords correctly
> Fix keywords formats in NormalRightRow

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
**Closes Issue**: #33 
replace `<br />` tags in blank line paddings
- replaced br with null values
- adjusted min-height of rows and lines so that blank lines and rows align the heights between left and right panel
**Results**
and
> Replace br tags in blank line paddings

- package.json
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/README.md
- src/components/SchemaTable/index.jsx
- yarn.lock
**Closes Issue** #14 & #30 
create a method to render object type schemas
**Results**
> Create renderObject() method

- .gitignore
`yarn build` outputs artifacts in `build/` rather than `lib/`.
> Add build directory to gitignore

- README.md
- src/components/SchemaTable/index.jsx
- src/components/index.js
- src/index.jsx
- src/theme.js
**Closes Issue** #21 
enable `<SchemaTable />` component to accept custom themes to make the viewer customizable
- ~refactored `<App />` into `<SchemaViewer />` which includes the stylization and theme customization for the schemaTable~
- ~added example of `<SchemaViewer />` with custom theme~
- added description for theme customization in `Readme.md`
- export `SchemaTable` component
> Add material-ui theme customization

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/Tooltip/index.jsx
- src/theme.js
**Closes Issue** #36 
- vertically center the icon with the tooltip text
- replace blanklines Typography component with div element
- add more padding to highlighted text and fix font-size and position if necessary
- replaced blanklines Typography component with div element
- refactored `<Tooltip />` into its own separate component
- vertically centered the icon for the tooltip text
- fixed height or rows and lines + added padding for highlighted text (for `types` in left panel)
**Result Screenshot**
> Fix position of icon and highlighted text

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/README.md
- src/components/SchemaTable/index.jsx
**Closes** #24 
apply indentations and prefix to nested structures
**Result**
- `contains` keyword in array type
- `required` properties in object type
> Apply indentations and prefix to nested structures

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/README.md
- src/components/SchemaTable/index.jsx
Closes #32 
create a method to render combination type schemas (allOf, anyOf, oneOf, not)
**Results**
> Create renderCombination() method

- .neutrinorc.js
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/utils/constants.js
Closes #44 
refactor `skipKeywords` inside `src/utils/constant.js`
**Applied changes**
> Refactor skipKeywords constants from row components

- src/components/NormalRightRow/index.jsx
Closes #50 
fix UI bug in display for `default` keyword in NormalRightRow
**Result**
> Fix display for default keyword in NormalRightRow

- .neutrinorc.js
- src/components/NormalLeftRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/utils/constants.js
- src/utils/schemaTree.js
Closes #60 
prefix custom keywords with an underscore (to distinguish them from schema fields)
> Add custom keywords in schema

- src/components/Header/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/SchemaViewer/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/components/SourceView/index.jsx
- src/utils/prop-types.js
- src/utils/schemaTree.js
Closes #37 
| table mode | source mode |
|:---|:---|
| <img src="https://user-images.githubusercontent.com/29671309/74140349-405df380-4c38-11ea-8064-2dcefb4d56ef.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/29671309/74140383-4d7ae280-4c38-11ea-869e-1966b1580da7.png" width="250px" /> |
> Add mode feature to viewer

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/OverflowLine/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/Tooltip/index.jsx
- src/utils/constants.js
- src/utils/prop-types.js
- src/utils/schemaTree.js
Closes #51 
Fix multiple chip and long description display
- tooltip when description is too long, title displays before description
- chips alphabetically displayed, max 3 chips per line
> Improve UI for keywords display in NormalRightRow

- README.md
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
Closes #66 
add style to color chip components
**Result Screenshots**
- Dark theme
- Yellow-Bluegrey Theme:
> Add style to chip components

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/utils/constants.js
Closes #67 
make `required` and `contains` symbol display consistent
> Improve UI for prefix in NormalLeftRow

- README.md
- src/components/Header/index.jsx
- src/components/NormalLeftRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/components/SourceView/index.jsx
Closes #74 
| type block | expand/shrink button | 
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/29671309/74415625-12bab980-4e87-11ea-8fda-ac8eea5e9a60.png) | ![image](https://user-images.githubusercontent.com/29671309/74415516-dc7d3a00-4e86-11ea-9afb-f8d0e620bc75.png) | 
| __comments__ | __grid borders__ |
| ![image](https://user-images.githubusercontent.com/29671309/74419097-be1a3d00-4e8c-11ea-9c25-4efd471de3d1.png) | ![image](https://user-images.githubusercontent.com/29671309/74419302-089bb980-4e8d-11ea-9c20-e159ccfe5314.png) |
> Fix color implementation of schemaTable

- schemas/basicDataTypes/miscellaneous/multiple-type.json
- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/utils/constants.js
- src/utils/prop-types.js
Closes #68 
simply display multiple types without any validation keyword matching
> Add feature to support multiple type specification

- schemas/basicDataTypes/miscellaneous/multiple-type.json
- schemas/basicDataTypes/miscellaneous/no-type.json
- src/components/NormalLeftRow/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/utils/constants.js
Closes #64 
- if a type is not specified, display ⚠️ icon in the left row with tooltip to instruct user to refer to the source instead
> Fix missing type keyword in schema cases

- src/components/NormalLeftRow/index.jsx
- src/components/NormalRightRow/index.jsx
Closes #80 
fix key error in `createTitleLine()` method in NormalRightRow
> Fix object key error

- src/components/Header/index.jsx
- src/components/OverflowLine/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/index.jsx
- src/theme.js
- src/utils/theme.js
Closes #88 
- Apply Taskcluster theme color to custom theme example in Storybook
- Fix color implementation where needed
| Dark Theme | Light Theme |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/29671309/75133508-701ff780-571e-11ea-83b8-79c4da51beb6.png) | ![image](https://user-images.githubusercontent.com/29671309/75133585-b412fc80-571e-11ea-94d0-fe26d020aa33.png) |
> Change Storybook custom theme example to Taskcluster theme

- .neutrinorc.js
- README.md
- src/components/Chip/index.jsx
- src/components/NormalRightRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/SchemaViewer/index.stories.js
- src/components/SourceView/index.jsx
- src/components/Tooltip/index.jsx
> Refactor chip to custom component

- src/utils/constants.js
- src/utils/prop-types.js
- src/utils/schemaTree.js
Closes #94 
- Schema Viewer component takes schemas and references required with `$id` fields
- SchemaTree and any tree nodes required in NormalLeftRow and NormalRightRow uses a sanitized version with an `_id` field instead
> Fix $id prop error in Schema types

- package.json
- src/components/Markdown/index.jsx
- yarn.lock
Remove `markdown-it-highlightjs` package dependency since we don't use this (and because it makes the entire component heavy)
> Remove markdown-it-highlightjs package dependency

- src/components/Header/index.jsx
- src/components/NormalLeftRow/index.jsx
- src/components/SchemaTable/index.jsx
- src/components/Tooltip/index.jsx
> UI enhancements

- README.md
- src/components/index.js
- src/index.jsx
This documents the import path used by Taskcluster, which seems to work.
If instead one uses
```
import SchemaViewer from 'material-ui-json-schema-viewer';
...
<SchemaViewer schema={..} references={..} />
```
then React complains,
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
The other working option is
```
import SchemaViewer from 'material-ui-json-schema-viewer';
...
<SchemaViewer.SchemaViewer schema={..} references={..} />
```
But this does not work:
```
import { SchemaViewer } from 'material-ui-json-schema-viewer';
...
<SchemaViewer schema={..} references={..} /> /* DOES NOT WORK */
```
> document library import path

- src/components/SchemaTable/LeftCell.jsx
To  include a colon after all properties on the left cell of the Schema Table component.
Closes #116 .
~~After fixing the bug, it was used the Prettier code formatter. Therefore, this PR includes some "prettifying" minor modifications in some additional lines in the same file in which the bug was found. If these modifications should be avoided, just let me know and I revert them.~~
Alright, I noticed ESLint doesn't like that kind of modifications. Now I just did the strictly necessary modifications in the code to fix the bug.
> Add a colon after all properties on the left (cell)

- src/components/SchemaTable/LeftCell.jsx
Change the font family of the left panel (Schema Table component) to "monospace".
Closes #115 .
@djmitche, @helfi92, please, check if the font size looks fine to you.
I modified the "fontFamily" property on the "name" and "code" class names (in the "makeStyles()" Material-UI function, which starts on line 22 from LeftCell.jsx).
> Change font family to monospace on the left panel
